### ISSUE TITLE
Unable to add new manual test plan

### ISSUE THREAD

**Issue by chase-qi** [Linaro/qa-reports#1]
On this page https://staging-qa-reports.linaro.org/#/testplan/
Click the "+" button, it shows a running gear, but after a long wait, it still hangs there.

**Comment by xando** [comment]
Right, it looks like I broke something with recent deploy. This and #2 are related (same error message)

I'm on it.

**Comment by terceiro** [comment]
just FWIW, it works for me right now

**Comment by xando** [comment]
Yes, it was fixed few hours ago
