### ISSUE TITLE
Feature request: bug attaching is needed for failed test items.

### ISSUE THREAD

**Issue by chase-qi** [Linaro/qa-reports#3]

**Comment by xando** [comment]
Hi @chase-qi 

By tests items you mean single tests inside test job, or test job. Also this feature is in progress.

**Comment by chase-qi** [comment]
Hi, 
Thanks for your replay. Good to know it is under developing. I mean single tests inside test job.

**Comment by xando** [comment]
@chase-qi, @mwasilew The feature preview is done and deployed to staging. Here is an example link.
https://staging-qa-reports.linaro.org/#/testjob/5f00df108697458a9ce37f10611a7863/edit/

Please let me know what you think.

**Comment by chase-qi** [comment]
Tested with Bugzilla/linaro and Bugzilla/96boards, works like a charm!
