### ISSUE TITLE
The marker "*****@linaro.org" still exists

### ISSUE THREAD

**Issue by xando** [Linaro/qa-reports#5]
https://staging-qa-reports.linaro.org/#/testjob/3e5a5c8ead794586844f68ead542a88d/edit/ I am able to click pass/skip/fail button to update test results on this page. String "by chase.qi@linaro.org" will added. When I click the pass/skip/fail again, test result can be removed, but the marker "by chase.qi@linaro.org" still exists. If I refresh the whole page, the string will disappear.

**Comment by xando** [comment]
@mwasilew @chase-qi

This is fixed and deployed to staging. 
The direct link to test it:
https://staging-qa-reports.linaro.org/#/testjob/5f00df108697458a9ce37f10611a7863/edit/

**Comment by chase-qi** [comment]
fixed.
