### ISSUE TITLE
Unable to save new test plan

### ISSUE THREAD

**Issue by chase-qi** [Linaro/qa-reports#7]
On this page https://staging-qa-reports.linaro.org/#/testplan/, click "+" button, input test plan name and select some test cases, then click "save" button, there is no feedback there. Go back to last page and refresh it, the new test plan didn't appear.

**Comment by chase-qi** [comment]
Modifications on the "Manual Test Plan" can not be saved either.
https://staging-qa-reports.linaro.org/#/testplan/2/

**Comment by xando** [comment]
fixed, and to https://staging-qa-reports.linaro.org
