### ISSUE TITLE
Unable to add manual test plan to test jobs

### ISSUE THREAD

**Issue by chase-qi** [Linaro/qa-reports#8]
On page https://staging-qa-reports.linaro.org/#/, click the first build "https://staging-qa-reports.linaro.org/#/execution/14637/", I can some manual test plans has been added. Then I tried to add manual test plan to the second build "https://staging-qa-reports.linaro.org/#/execution/14638/" by selecting test plan and clicking "+" button, but nothing happens.

**Comment by chase-qi** [comment]
Browser log
POST https://staging-qa-reports.linaro.org/api/test-job/ 403 (Forbidden)

**Comment by xando** [comment]
I was able to reproduce the issue working on it

**Comment by xando** [comment]
fixed, and to https://staging-qa-reports.linaro.org
